Built in functions in numpy with examples

In [1]:
#1. Numpy N dimension array(NDarray): A fixed size multidimensional contaner of simmilar size items
import numpy as np
a = np.array([3,5,6,7,8,])
print (a)

[3 5 6 7 8]


In [2]:
#2. Data type objects(np.dtype): describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted
a = np.array([3,5,6,7,8,])
print (a.dtype)

int32


In [5]:
#3. Add
a = np.array(['ben','sarah','okon','precious'])
b= np.array(['edidiong','6',8,8,5])
char 
char.add(a,b)

NameError: name 'char' is not defined

In [3]:
#4 Making a copy of a numpy 
import numpy as np
a = np.array([1, 2, 3, 4, 5])
x = a.copy()
a[0] = 42

print(a)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
#5 Making a view of a numpy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [5]:
#6 Checking if array owns it's data
import numpy as np
a = np.array([3,4,6,7,8])
x = a.copy()
y = a.view()

print(x.base)
print(y.base)


None
[3 4 6 7 8]


In [6]:
#7 checking shape of an array
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [8]:
#8 Creating array with defined dimension
import numpy as np
x = np.array([1,2,3,4], ndmin = 5)
print (x)
print (x.shape)


[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [10]:
#9 Reshaping an array
import numpy as np
d = np.array([1,2,3,4,5,6,7,8,9,12,12,13])
p = d.reshape(4,3)#reshaping into dimension with 4 arrays with 3 eelements each
print (p)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [12 12 13]]


In [13]:
#10 Flattening an array, converting multidimensional array into a 1d array
import numpy as np
x = np.array([[2,3,4],[5,7,9]])
print (x.ndim)
z = x.reshape(-1)
print (z)

2
[2 3 4 5 7 9]


In [18]:
#11 iterating arrays
import numpy as np
c = np.array([[4,5,7,8],[5,6,7,9]])
for b in c:
    for q in b:
        print(q)

4
5
7
8
5
6
7
9


In [28]:
#12 ndditer function, a helping function that solves basic issues in iteration
import numpy as np
v = np.array([[[4,5,],[6,7]],[[9,10],[3,8]]])
for x in np.nditer(v):
    print (x)

4
5
6
7
9
10
3
8


In [36]:
#13 op_dtypes, passes expected datatype while iterating
import numpy as np
t = np.array([1,2,4])
for x in np.nditer(t, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'4'


In [39]:
#14 enumerated iteration using ndemnumerate()
import numpy as np
d = np.array([1,2,3])
for idx, x in np.ndenumerate(d):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [40]:
#15 concatenatee function; to join numpy arrays
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [41]:
#16 stack function, same as concatenation yet done along a new axis
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array ([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print (arr)

[[1 4]
 [2 5]
 [3 6]]


In [43]:
#17 horizontal stack function, stacks along rows
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print (arr)

[1 2 3 4 5 6]


In [44]:
#18 Vertical stack function, stacks along columns
import numpy as np
arr1 = np.array ([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)


[[1 2 3]
 [4 5 6]]


In [47]:
#19 splitting, reverse of joining
import numpy as np
arr = np.array([1,2,3,4,5])
z = np.array_split(arr,3)
print (z)

[array([1, 2]), array([3, 4]), array([5])]


In [49]:
#20search function. search for array with certain value
import numpy as np
arr = np.array([1,2,3,4,5,6,4,6,4])
x =np.where(arr==4)
print(x)

(array([3, 6, 8], dtype=int64),)
